# Generated by Django 2.1.5 on 2020-11-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(help_text='Enter the startup name', max_length=100)),
                ('poc_name', models.CharField(help_text='Enter the Point of Contact-Name', max_length=100)),
                ('poc_email', models.EmailField(help_text='Enter the Point of Contact-Email', max_length=100)),
                ('profile_doc', models.FileField(storage='/Users/ravi/Desktop/task/filestore/startups', upload_to='')),
                ('incentives', models.CharField(help_text='Incentives', max_length=500)),
                ('duration', models.CharField(help_text='Enter the duration of program', max_length=20)),
                ('website', models.CharField(blank=True, help_text='Enter website,if any', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=100)),
                ('middle_name', models.CharField(help_text='Enter middle name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=100)),
                ('age', models.IntegerField(help_text='Enter your age')),
                ('rollno', models.CharField(help_text='Enter Roll No.', max_length=20)),
                ('student_email', models.EmailField(help_text='Enter email', max_length=100)),
                ('dept', models.CharField(help_text='Enter your department', max_length=50)),
                ('resume', models.FileField(storage='/Users/ravi/Desktop/task/filestore/students', upload_to='')),
            ],
        ),
    ]
