# Generated by Django 2.1.5 on 2020-11-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='profile_doc',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
