# Generated by Django 2.1.5 on 2020-11-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0003_startup_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='companies',
        ),
        migrations.AddField(
            model_name='student',
            name='companies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecell.Startup'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='profile_doc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
