# Generated by Django 2.1.5 on 2020-11-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0004_auto_20201109_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='profile_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
