# Generated by Django 2.1.5 on 2020-11-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0006_auto_20201109_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='startup',
            name='incentives',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='startup',
            name='poc_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='poc_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
