# Generated by Django 2.1.5 on 2020-11-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0007_auto_20201109_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('poc_name', models.CharField(max_length=100)),
                ('poc_email', models.EmailField(max_length=100)),
                ('profile_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('incentives', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=20)),
                ('website', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='companies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecell.InternshipRole'),
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
        migrations.AddField(
            model_name='internshipquestion',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecell.InternshipRole'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecell.Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecell.InternshipRole'),
        ),
        migrations.AddField(
            model_name='internshipanswer',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecell.Student'),
        ),
        migrations.AddField(
            model_name='internshipanswer',
            name='internship_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecell.InternshipQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('applicant', 'internship')},
        ),
        migrations.AlterUniqueTogether(
            name='internshipanswer',
            unique_together={('applicant', 'internship_question')},
        ),
    ]
