# Generated by Django 2.1.5 on 2020-11-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0008_auto_20201110_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='companies',
            new_name='roles',
        ),
    ]
