# Generated by Django 2.1.5 on 2020-11-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0009_auto_20201110_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiprole',
            name='id',
        ),
        migrations.AddField(
            model_name='internshiprole',
            name='role_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
