# Generated by Django 2.1.5 on 2020-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0010_auto_20201110_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiprole',
            name='role_id',
        ),
        migrations.AddField(
            model_name='internshiprole',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
