# Generated by Django 2.1.5 on 2020-11-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecell', '0011_auto_20201110_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('rollno', 'roles')},
        ),
    ]
